### ISSUE TITLE
Code Upload Failed (USER)

### ISSUE THREAD

**Issue by mepritam** [rdas6313/Quick-paste#1]
While uploading code via user mode, I am not getting anything. 
08:32 PM, 17 Sep 2022  -> Error: UserPastesCommand: show_quick_panel() takes from 3 to 6 positional arguments but 7 were given

**Comment by rdas6313** [comment]
Since API has changed in sublime text 4 and you are using sublime text 3. That's why you are having that error. Move to sublime text 4 to avoid such errors.
